filebeat.inputs:
  - type: container
    paths:
      - '/var/lib/docker/containers/*/*.log'
  - type: log
    paths:
      - '/usr/share/server-app/logs/*.log'

output.logstash:
    hosts: ["logstash:5044"]